export const EMOTIONS_ENUM = {
  SAD: "sadness",
  ANGER: "anger",
  FEAR: "fear",
  SURPRISE: "surprise",
  DISGUST: "disgust",
  JEALOUSY: "jealousy",
  GUILT: "guilt",
  SHAME: "shame",
  CONFUSION: "confusion",
  ANXIETY: "anxiety",
  FRUSTRATION: "frustration",
};

export const PHYSICAL_STATES_ENUM = {
  NAUSEA: "nausea",
  FATIGUE: "fatigue",
  PAIN: "pain",
  DIZZINESS: "dizziness",
  WEAKNESS: "weakness",
  NUMBNESS: "numbness",
  PALPITATIONS: "palpitations",
  SHORTNESS_OF_BREATH: "shortness of breath",
  HEADACHE: "headache",
  SWEATING: "sweating",
  TINGLING: "tingling",
  BLURRED_VISION: "blurred vision",
  TREMORS: "tremors",
  CRAMPS: "cramps",
  FLUSHING: "flushing",
  LETHARGY: "lethargy",
  LOSS_OF_APPETITE: "loss of appetite",
  CHILLS: "chills",
  SENSITIVITY_TO_LIGHT: "sensitivity to light",
  SENSITIVITY_TO_SOUND: "sensitivity to sound",
};

export const EXTERNAL_STIMULI_ENUM = {
  PEOPLE: "people",
  MEDIA: "media",
  MEMORY: "memory",
  SITUATION: "situation",
  PLACE: "place",
  THING: "thing",
};

export const FEELING = {
  EXCLUDED: "excluded",
  POWERLESS: "powerless",
  UNHEARD: "unheard",
  JUDGED: "judged",
  BLAMED: "blamed",
  DISRESPECTED: "disrespected",
  NEGLECTED: "neglected",
  IGNORED: "ignored",
  LONELY: "lonely",
  FORGOTTEN: "forgotten",
  UNSAFE: "unsafe",
  UNLOVED: "unloved",
  FRUSTRATED: "frustrated",
  MANIPULATED: "manipulated",
  OUTOFCONTROL: "out of control",
  MISUNDERSTOOD: "misunderstood",
  OVERWHELMED: "overwhelmed",
  HELPLESS: "helpless",
  INSECURE: "insecure",
  ANXIOUS: "anxious",
  GUILTY: "guilty",
  VULNERABLE: "vulnerable",
  HOPELESS: "hopeless",
  DISAPPOINTED: "disappointed",
  BETRAYED: "betrayed",
  ISOLATED: "isolated",
};

export const CONSEQUENCES = {
  INTENSE_EMOTIONS: "intense emotions",
  PHYSIOLOGICAL_CHANGES: "physiological changes",
  FIGHT_OR_FLIGHT: "fight or flight",
  WITHDRAWAL: "withdrawal",
  RUMINATION: "rumination",
  IMPAIRED_DECISION_MAKING: "impaired decision making",
  RELATIONSHIP_STRAIN: "relationship strain",
  COMMUNICATION_BREAKDOWN: "communication breakdown",
  STRESS: "stress",
  ANXIETY: "anxiety",
  DEPRESSION: "depression",
  SUBSTANCE_USE: "substance_use",
  SLEEP_DEPRIVATION: "sleep deprivation",
};

export const SOLUTIONS = {
  ANTICIPATION: "anticipation",
  AVOIDANCE: "avoidance",
  ACCEPTANCE: "acceptance",
  BREAK: "break",
  DELAY: "delay",
  REST: "rest",
  BOUNDARIES: "boundaries",
  ASK: "ask for help",
  DISTRACTION: "distraction",
  COMMUNICATION: "communication",
};
